### ISSUE TITLE
DEFCONSTANT used on STRINGS

### ISSUE THREAD

**Issue by phoe** [charJe/portal#1]
https://github.com/quicklisp/quicklisp-projects/issues/1962#issuecomment-761592698

https://github.com/charJe/portal/blob/7635c372c919e3f2af22fc1a6f2c73af199c232d/portal.lisp#L9-L14

This invokes undefined behavior on redefinition.

Use `alexandria:define-constant` with a `string=` test instead.

**Comment by charJe** [comment]
2c8b759 Thanks for the suggestion, after finally reading SBCL manual (2.3.4 Defining Constants) I understand this issue.
