### ISSUE TITLE
GNU licenses prohibited in most commercial environments

### ISSUE THREAD

**Issue by snunez1** [charJe/portal#2]
Most commercial entities prohibit anything GNU (even LGPL -- rightly or wrongly). Will you consider changing the license to MIT, BSD or Apache?

**Comment by charJe** [comment]
I selected the license to protect the freedom and quality of this software. The llgpl is quite usable even for proprietary software; I cannot help a company's ignorant policy. I would very much prefer everyone use the llgpl version of this software, but If a commercial entity really doesn't want to use it with the given license, they can email me and _maybe_ we can sort out some special alternative.
